### ISSUE TITLE
run 不起来

### ISSUE THREAD

**Issue by LemonBabyluo** [fluttercandies/wechat_flutter#27]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Project base configurations detected, removing.
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A path_provider_windows
      A photo_manager
      A video_player_web
      - Flutter
      - audioplayers
      - camera
      - connectivity
      - dim
      - flutter_image_compress
      - flutter_sound
      - image_picker
      - open_file
      - package_info
      - path_provider
      - path_provider_linux
      - path_provider_macos
      - permission_handler
      - shared_preferences
      - sqflite
      - url_launcher
      - video_player
      - webview_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `dim` from `.symlinks/plugins/dim/ios`
    -> Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
    -> Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `open_file` from `.symlinks/plugins/open_file/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_linux` from `.symlinks/plugins/path_provider_linux/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `path_provider_windows` from `.symlinks/plugins/path_provider_windows/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `photo_manager` from `.symlinks/plugins/photo_manager/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    -> Fetching podspec for `video_player_web` from `.symlinks/plugins/video_player_web/ios`
    -> Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path downloaded: all_pods_versions_2_7_4.txt, save ETag: W/"5f85230c-412"
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.0/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.0/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.1/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.1/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.11/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.11/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.2/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.2/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.3/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.3/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.4/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.4/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.5/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.5/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.6/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.6/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.8/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.8/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.9/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.9/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.12/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.12/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.7/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.7/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/1.0.1/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/1.0.1/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/1.0.3/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/1.0.3/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/1.0.4/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/1.0.4/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/0.9.10/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/0.9.10/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/1.0/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/1.0/YYModel.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/2/7/4/YYModel/1.0.2/YYModel.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/2/7/4/YYModel/1.0.2/YYModel.podspec.json
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.6/YYModel.podspec.json, save ETag: W/"263-IwM9Rx90cdfimHWpYN9CsEQp7Og"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.12/YYModel.podspec.json, save ETag: W/"2aa-M6J/QamV9MNv+BeEIbrJ8iGpx+o"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.8/YYModel.podspec.json, save ETag: W/"263-Taa1xCqFDlyByADeW6aa/mdcbm8"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.10/YYModel.podspec.json, save ETag: W/"2aa-/qUDc71TzQTJqQ5YDArFYcXRAJ4"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.5/YYModel.podspec.json, save ETag: W/"263-3SvckJf4qQxTUSqH1V0oNAreE3E"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.7/YYModel.podspec.json, save ETag: W/"263-iPS97CWXWo9kLaoLtXKwOaOrHbE"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/1.0.4/YYModel.podspec.json, save ETag: W/"2a8-Kn/dlqqkuGqCTibQxRfeiSjASzA"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.0/YYModel.podspec.json, save ETag: W/"263-5nJQQq8OvWeAT3oiRtsfJkszP8E"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.4/YYModel.podspec.json, save ETag: W/"263-WkeNw70T0r6VICZgW3fB7ayGASg"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.9/YYModel.podspec.json, save ETag: W/"2a8-bi9mq9xCmz9UL8UlsmL0G2L8KuI"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/1.0.1/YYModel.podspec.json, save ETag: W/"2a8-eU8IIKmpcDYVvBZqqOM2q69CLCs"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.1/YYModel.podspec.json, save ETag: W/"263-ZZA1oZt4Od2/p2G06achxonBHik"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.2/YYModel.podspec.json, save ETag: W/"263-jjO3jtrEA8wTLQF88CLQPzgiFHA"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.3/YYModel.podspec.json, save ETag: W/"263-LWx9OpUv6zjbdJHA72LE282F8Ck"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/1.0.3/YYModel.podspec.json, save ETag: W/"2a8-YxQsLwfFyMnRwmFonPOCfqarKIY"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/1.0/YYModel.podspec.json, save ETag: W/"2a4-JwSKJisVDDDiU/cXdkCOIdbv6Mw"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/1.0.2/YYModel.podspec.json, save ETag: W/"2a8-ekZ+/0WuNkHDPvsTbCYtM7b0jBo"
      CDN: trunk Relative path downloaded: Specs/2/7/4/YYModel/0.9.11/YYModel.podspec.json, save ETag: W/"2aa-gtnj+s2EuAmo1eeuoXDHIpyiQ0s"
      CDN: trunk Relative path: Specs/2/7/4/YYModel/1.0.4/YYModel.podspec.json modified during this run! Returning local
      CDN: trunk Relative path downloaded: all_pods_versions_6_1_0.txt, save ETag: W/"5f8520b4-469"
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.4.479/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.4.479/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.4.627/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.4.627/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.4.716/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.4.716/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.4.900/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.4.900/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.5.111/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.5.111/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.5.15/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.5.15/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.5.55/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.5.55/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.1/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.1/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.100/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.100/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.101/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.101/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.17/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.17/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.21/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.21/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.5/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.5/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.51/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.51/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.54/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.54/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.58/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.58/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.6.8/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.6.8/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.7.1/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.7.1/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.7.10/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.7.10/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.7.2/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.7.2/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.8.1/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.8.1/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.8.10/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.8.10/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.8.50/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.8.50/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.9.1/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.9.1/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/4.5.45/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/4.5.45/TXIMSDK_iOS.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/6/1/0/TXIMSDK_iOS/5.0.6/TXIMSDK_iOS.podspec.json to https://cdn.jsdelivr.net/cocoa/Specs/6/1/0/TXIMSDK_iOS/5.0.6/TXIMSDK_iOS.podspec.json
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.4.716/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-k5HuK/L1E8HjjW+zA7VZjYUZUro"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.5.55/TXIMSDK_iOS.podspec.json, save ETag: W/"369-rdZyAcZNCoZo5L+rTSH4PoB10Ao"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.5.15/TXIMSDK_iOS.podspec.json, save ETag: W/"369-fPRn3HyQ8pS4lOintwBLznrP0zI"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.5.45/TXIMSDK_iOS.podspec.json, save ETag: W/"369-ZREEjWRx9fSM8H68BdCxigKS60E"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.58/TXIMSDK_iOS.podspec.json, save ETag: W/"369-1CMczYoEX1TKBNAI26Rv2/JWh/s"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.5.111/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-XJUkKNWkTzw19PpdN89KrsjxkOY"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.1/TXIMSDK_iOS.podspec.json, save ETag: W/"367-/oXHaYluv/zKGR37JNk2GN1zbWI"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.7.1/TXIMSDK_iOS.podspec.json, save ETag: W/"367-JQayfP3yrqPkQztnhwdV06FLNYw"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.4.627/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-Y3r4M4KHCn2lDNBe6/mn4oBECIU"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.54/TXIMSDK_iOS.podspec.json, save ETag: W/"369-x1F1uEPCrf6xN91UqS13Idj+U9s"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.8/TXIMSDK_iOS.podspec.json, save ETag: W/"367-T5kXaNbuByLoa7EonzKbK22tcP8"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.7.2/TXIMSDK_iOS.podspec.json, save ETag: W/"367-DTwpKSDJa6CLb6jv3mXHSI60Nqc"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.17/TXIMSDK_iOS.podspec.json, save ETag: W/"369-6Y+ewmItqTvD6lQGpaKClpLJS2o"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.4.479/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-mvhKexMule5TICNeEACU0Qcu76E"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.21/TXIMSDK_iOS.podspec.json, save ETag: W/"369-GyID3Pgm3p6Tdd78sqR4NqczVj8"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.101/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-8IBHLUwQyysLxY+G80Dx6KSdNK0"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.8.1/TXIMSDK_iOS.podspec.json, save ETag: W/"367-rzBAtxj0tzxELeNWAswZDwSM/Lw"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.5/TXIMSDK_iOS.podspec.json, save ETag: W/"367-46j/+ZzY8HglftODsXaqQVJRcSc"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.8.50/TXIMSDK_iOS.podspec.json, save ETag: W/"369-rib3jgKOAb7tRxJ+pr3gPBEVYgg"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.100/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-NITPWROfi5QgKkav9kf6H2yE/ZA"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.7.10/TXIMSDK_iOS.podspec.json, save ETag: W/"369-aU10vnJ06dlLZNl9/R3U870p8VA"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.4.900/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-VMBMCAfM8MQGNm74bP9mPqJ34jU"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.51/TXIMSDK_iOS.podspec.json, save ETag: W/"369-PnG83HqClDfXt9EdiEKT4Vvovt8"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.8.10/TXIMSDK_iOS.podspec.json, save ETag: W/"369-F94v73hveIQ2h8x72VknWe3S7As"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.9.1/TXIMSDK_iOS.podspec.json, save ETag: W/"367-WH4l+otCyfIou5BlCEJw+mmQGQ8"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/4.6.102/TXIMSDK_iOS.podspec.json, save ETag: W/"36b-4vaRMIufJ/UbqT1Tr3ElTP4b+lw"
      CDN: trunk Relative path downloaded: Specs/6/1/0/TXIMSDK_iOS/5.0.6/TXIMSDK_iOS.podspec.json, save ETag: W/"410-zGX5f7RUgRdX8NcdVKFXJrmVwNc"
      CDN: trunk Relative path: Specs/6/1/0/TXIMSDK_iOS/5.0.6/TXIMSDK_iOS.podspec.json modified during this run! Returning local
      CDN: trunk Relative path: all_pods_versions_c_7_9.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/c/7/9/Reachability/3.2/Reachability.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_5_d_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/5/d/c/Mantle/2.1.1/Mantle.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_e_9_d.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/e/9/d/SDWebImageWebPCoder/0.6.1/SDWebImageWebPCoder.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "photo_manager":
      In Podfile:
        photo_manager (from `.symlinks/plugins/photo_manager/ios`)

    Specs satisfying the `photo_manager (from `.symlinks/plugins/photo_manager/ios`)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by ahyangnb** [comment]
可以清理，

**Comment by ahyangnb** [comment]
顺便检查下pod的源配置
